// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macOS - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: "AIzaSyDKdfFbJ3yK3XTXLAF8O8k7dI8qLByVBp0",
//     authDomain: "flutter-chat-app-59d40.firebaseapp.com",
//     projectId: "flutter-chat-app-59d40",
//     storageBucket: "flutter-chat-app-59d40.firebasestorage.app",
//     messagingSenderId: "286746587055",
//     appId: "1:286746587055:web:275a795ede5553c4b4095a"
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: "AIzaSyDKdfFbJ3yK3XTXLAF8O8k7dI8qLByVBp0",
//     appId: "1:286746587055:android:xxxxxxxxxxxxx",
//     messagingSenderId: "286746587055",
//     projectId: "flutter-chat-app-59d40",
//     storageBucket: "flutter-chat-app-59d40.firebasestorage.app",
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: "AIzaSyDKdfFbJ3yK3XTXLAF8O8k7dI8qLByVBp0",
//     appId: "1:286746587055:ios:xxxxxxxxxxxxx",
//     messagingSenderId: "286746587055",
//     projectId: "flutter-chat-app-59d40",
//     storageBucket: "flutter-chat-app-59d40.firebasestorage.app",
//     iosBundleId: 'com.example.chatApp',
//   );
// }

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';  // ← Keep this now
import 'screens/auth_screen.dart';
import 'screens/chat_list_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,  // ← Keep this now
  );
  runApp(const MyApp());
}